// <auto-generated/>
#pragma warning disable CS0618
using DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookings;
using DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookingsPerUser;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic
{
    /// <summary>
    /// Builds and executes requests for operations under \bl\BusinessLogic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessLogicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GetBookings property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookings.GetBookingsRequestBuilder GetBookings
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookings.GetBookingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetBookingsPerUser property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookingsPerUser.GetBookingsPerUserRequestBuilder GetBookingsPerUser
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.GetBookingsPerUser.GetBookingsPerUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.BusinessLogicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessLogicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bl/BusinessLogic", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.BusinessLogicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessLogicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bl/BusinessLogic", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
