// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Booking : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bookingEnd property</summary>
        public DateTimeOffset? BookingEnd { get; set; }
        /// <summary>The bookingStart property</summary>
        public DateTimeOffset? BookingStart { get; set; }
        /// <summary>The changeDate property</summary>
        public DateTimeOffset? ChangeDate { get; set; }
        /// <summary>The creationDate property</summary>
        public DateTimeOffset? CreationDate { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The desk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk? Desk { get; set; }
#nullable restore
#else
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk Desk { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.User? User { get; set; }
#nullable restore
#else
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/> and sets the default values.
        /// </summary>
        public Booking()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookingEnd", n => { BookingEnd = n.GetDateTimeOffsetValue(); } },
                { "bookingStart", n => { BookingStart = n.GetDateTimeOffsetValue(); } },
                { "changeDate", n => { ChangeDate = n.GetDateTimeOffsetValue(); } },
                { "creationDate", n => { CreationDate = n.GetDateTimeOffsetValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "desk", n => { Desk = n.GetObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk>(global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.User>(global::DA.SharedDeskPlanner.WebAPI.Client.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("bookingEnd", BookingEnd);
            writer.WriteDateTimeOffsetValue("bookingStart", BookingStart);
            writer.WriteDateTimeOffsetValue("changeDate", ChangeDate);
            writer.WriteDateTimeOffsetValue("creationDate", CreationDate);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk>("desk", Desk);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
