// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InventoryItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The changeDate property</summary>
        public DateTimeOffset? ChangeDate { get; set; }
        /// <summary>The creationDate property</summary>
        public DateTimeOffset? CreationDate { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The desk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk? Desk { get; set; }
#nullable restore
#else
        public global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk Desk { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem"/> and sets the default values.
        /// </summary>
        public InventoryItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changeDate", n => { ChangeDate = n.GetDateTimeOffsetValue(); } },
                { "creationDate", n => { CreationDate = n.GetDateTimeOffsetValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "desk", n => { Desk = n.GetObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk>(global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("changeDate", ChangeDate);
            writer.WriteDateTimeOffsetValue("creationDate", CreationDate);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk>("desk", Desk);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk"/>, <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InventoryItem_desk : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk? Desk { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk Desk { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1? InventoryItemDeskMember1 { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1 InventoryItemDeskMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem.InventoryItem_desk();
                if("Desk".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Desk = new global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InventoryItemDeskMember1 = new global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Desk != null)
                {
                    return Desk.GetFieldDeserializers();
                }
                else if(InventoryItemDeskMember1 != null)
                {
                    return InventoryItemDeskMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Desk != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Desk>(null, Desk);
                }
                else if(InventoryItemDeskMember1 != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.InventoryItem_deskMember1>(null, InventoryItemDeskMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
