// <auto-generated/>
#pragma warning disable CS0618
using DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Bl
{
    /// <summary>
    /// Builds and executes requests for operations under \bl
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The BusinessLogic property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.BusinessLogicRequestBuilder BusinessLogic
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BusinessLogic.BusinessLogicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bl", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Bl.BlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bl", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
