@DA.SharedDeskPlanner.WebAPI_HostAddress = http://localhost:5295

###

@bookingID=1
GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/booking/{{bookingID}}

###

GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/booking

###

DELETE {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/booking/{{bookingID}}

###

GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/user

###

POST {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/user
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "name": "MM",
  "bookings": null,
  "deleted": false
}

###

GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/room

###

POST {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/room
Content-Type: application/json

{
  "name": "Kerker",
  "desks": null,
  "deleted": false
}

###

GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/desk

###

@deskID=1
GET {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/desk/{{deskID}}

###
@deskID=1
DELETE {{DA.SharedDeskPlanner.WebAPI_HostAddress}}/api/desk/{{deskID}}

###
