// <auto-generated/>
#pragma warning disable CS0618
using DA.SharedDeskPlanner.WebAPI.Client.Api.Booking;
using DA.SharedDeskPlanner.WebAPI.Client.Api.Desk;
using DA.SharedDeskPlanner.WebAPI.Client.Api.InventoryItem;
using DA.SharedDeskPlanner.WebAPI.Client.Api.Room;
using DA.SharedDeskPlanner.WebAPI.Client.Api.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Booking property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder Booking
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Desk property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Desk.DeskRequestBuilder Desk
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Desk.DeskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The InventoryItem property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.InventoryItem.InventoryItemRequestBuilder InventoryItem
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Api.InventoryItem.InventoryItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Room property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Room.RoomRequestBuilder Room
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Room.RoomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The User property</summary>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.User.UserRequestBuilder User
        {
            get => new global::DA.SharedDeskPlanner.WebAPI.Client.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
