// <auto-generated/>
#pragma warning disable CS0618
using DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.Item;
using DA.SharedDeskPlanner.WebAPI.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DA.SharedDeskPlanner.WebAPI.Client.Api.Booking
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Booking
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DA.SharedDeskPlanner.WebAPI.Client.api.Booking.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.Item.WithBookingItemRequestBuilder"/></returns>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.Item.WithBookingItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("bookingID", position);
                return new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.Item.WithBookingItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Booking", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Booking", rawUrl)
        {
        }
        /// <returns>A List&lt;global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking>(requestInfo, global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PutAsync(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PutAsync(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1"/>, <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingPostRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking? Booking { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking Booking { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1? BookingPostRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1 BookingPostRequestBodyMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPostRequestBody();
                if("Booking".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Booking = new global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BookingPostRequestBodyMember1 = new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Booking != null)
                {
                    return Booking.GetFieldDeserializers();
                }
                else if(BookingPostRequestBodyMember1 != null)
                {
                    return BookingPostRequestBodyMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Booking != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking>(null, Booking);
                }
                else if(BookingPostRequestBodyMember1 != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPostRequestBodyMember1>(null, BookingPostRequestBodyMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1"/>, <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingPutRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking? Booking { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking Booking { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1? BookingPutRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1 BookingPutRequestBodyMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingRequestBuilder.BookingPutRequestBody();
                if("Booking".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Booking = new global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BookingPutRequestBodyMember1 = new global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Booking != null)
                {
                    return Booking.GetFieldDeserializers();
                }
                else if(BookingPutRequestBodyMember1 != null)
                {
                    return BookingPutRequestBodyMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Booking != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Models.Booking>(null, Booking);
                }
                else if(BookingPutRequestBodyMember1 != null)
                {
                    writer.WriteObjectValue<global::DA.SharedDeskPlanner.WebAPI.Client.Api.Booking.BookingPutRequestBodyMember1>(null, BookingPutRequestBodyMember1);
                }
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
